businessandtrade-partners/spl-planner

- app/assets/javascripts/components/Calendar.vue
- app/assets/javascripts/components/Planner.vue
- fix sticky sidebar on safari
- fix user-select:none on safari
> fix highlighting calendar and sticky sidebar in safari

- app/views/components/file-download.njk
https://solirius.atlassian.net/browse/SPL-5
> removing prefilled paragraph message

- app/assets/javascripts/components/Planner.vue
- app/node-email.js
- app/node-email.test.js
- app/paths.js
- app/router.js
- app/views/feedback/feedback-confirmation.njk
- app/views/feedback/feedback.njk
- app/views/tabs/leave-summary.njk
- app/views/tabs/pay-summary.njk
- package-lock.json
- package.json
sending an email with the users feedback
> Spl 2/feedback form

- app/router.js
- app/views/summary.njk
https://solirius.atlassian.net/browse/SPL-33
https://solirius.atlassian.net/browse/SPL-34
> including ga tags in summary page for both visual and question planner

- app/views/tabs/leave-summary.njk
https://solirius.atlassian.net/browse/SPL-30
> including block count ga tags

- app/views/tabs/leave-summary.njk
- app/views/tabs/pay-summary.njk
https://solirius.atlassian.net/browse/SPL-64
> including next step texts

- app/assets/sass/application.scss
- app/views/eligibility/maternity-allowance.njk
- app/views/eligibility/paternity-leave-and-pay.njk
- app/views/eligibility/primary-initial-leave-and-pay.njk
- app/views/eligibility/primary-shared-parental-leave-and-pay.njk
- app/views/eligibility/secondary-shared-parental-leave-and-pay.njk
Reverts UKGovernmentBEIS/beis-spl-planner#156
> Revert "moving the hints to second radio button and getting rid of un-require…"

- app/constants.js
- test/unit/lib/blocks.test.js
https://solirius.atlassian.net/browse/SPL-289
Update statutory pay for April 8th 2024 (inclusive) onwards
> Update STATUTORY_MAXIMUM_PAY constant for April 2024

- test/features/adoption/secondary-leave-and-pay.spec.js
- test/features/surrogacy/child-due-date.spec.js
- test/features/surrogacy/secondary-leave-and-pay.spec.js
- test/fixtures/surrogacy/select-parental-order-leave-and-pay.js
- test/fixtures/surrogacy/select-partners-leave-and-pay.js
> Added surrogacy feature tests for secondary leave and pay and child due date. Added fixtures

- playwright.config.js
- reuse browser contexts
- use dot reporter for CI
- use one browser
> reduce CI run time:

- common/utils/session-data.js
- test/unit/common/utils/session-data.test.js
- correctly set arrayFormat for query string data containing planner leave weeks
> SPL-443 - bug fix: retain compulsory leave weeks when going back a page from planner

- .nycrc
- app/emailjs-mailer.js
- test/unit/app/config.test.js
- test/unit/app/filters.test.js
test coverage increased to 51%
> SPL 466a - increase test app folder coverage

- app/config.js
- app/emailjs-mailer.js
- app/router.js
- test/unit/app/config.test.js
- test/unit/app/emailjs-mailer.test.js
[SPL-475](https://solirius.atlassian.net/browse/SPL-475)
[SPL-472](https://solirius.atlassian.net/browse/SPL-472)
> SPL-475 & SPL-472 - Move env vars to config + add plannerOrEligibility param to emailJS

- app/filters.js
- app/lib/blocks.js
- app/validate.js
- package-lock.json
- test/unit/app/filters.test.js
- test/unit/app/skip.test.js
- test/unit/app/validate.test.js
upped coverage from 51.53% to 61.49%
/app folder files
- filters.js - above 80% coverage
- skip.js - 100%
- validate.js - 60% - planner method still needs testing
> SPL-466b - improve app folder test coverage

- app/views/tabs/leave-summary.njk
- test/features/scenarios/birth/leaveSummary/leave-summary-all-eligible.spec.js
[SPL-479](https://solirius.atlassian.net/browse/SPL-479)
> SPL-479 - Planner: Update "Notify employers"

- app/paths.js
- app/router.js
- app/views/layout.njk
- app/views/privacy-notice.njk
[SPL-462](https://solirius.atlassian.net/browse/SPL-462)
> SPL-462 - Create privacy policy

- app/views/privacy/cookies.njk
- common/browsered/index.js
- test/features/cookies.spec.js
- test/features/fixtures/select-cookies.js
[SPL-465](https://solirius.atlassian.net/browse/SPL-465)
> SPL-465 - Update cookie page cookie table

- app/views/includes/ga.njk
- app/views/includes/ga_head.njk
- app/views/includes/head.njk
- app/views/layout.njk
- gruntfile.js
- test/features/cookie-banner.spec.js
- test/features/google-analytics.spec.js
- test/features/nature-of-parenthood.spec.js
[SPL-468](https://solirius.atlassian.net/browse/SPL-468)
> SPL-468 - Update Google Tag Manager Script

- gruntfile.js
- package.json
- Add new compile:prod script for building for production
- update browserslist in package.json
> SPL-498 - Set NODE_ENV to 'production' in gruntfile.js for production build

- server.js
[SPL-501](https://solirius.atlassian.net/browse/SPL-501)
> SPL-501 - typo in govukfrontend import in server.js

- app/views/privacy-notice.njk
- package-lock.json
https://solirius.atlassian.net/browse/SPL-481
Playwright build step for installing browsers failed - updating to latest playwright version should fix this. https://github.com/microsoft/playwright/issues/33051
> SPL-481 - update privacy-notice content

- .github/workflows/planner.yml
- app/assets/javascripts/components/ShareLink.vue
- app/views/components/summary-tab-footer.njk
https://solirius.atlassian.net/browse/SPL-524
> SPL-254 - A - Headings

- .github/workflows/planner.yml
- app/assets/javascripts/components/Calendar.vue
- test/features/scenarios/adoption/child-live-in-date.spec.js
https://solirius.atlassian.net/browse/SPL-517
> SPL-517 - AA - Focus Obscured

- app/views/accessibility-statement.njk
https://solirius.atlassian.net/browse/SPL-546
> SPL-546 - Update Accessibility Statement

- app/assets/javascripts/components/Calendar.vue
- app/assets/sass/application.scss
- app/views/accessibility-statement.njk
https://solirius.atlassian.net/browse/SPL-534
> SPL-534 - A - Use of Colour

- app/assets/javascripts/components/Calendar.vue
- app/assets/javascripts/components/Planner.vue
https://solirius.atlassian.net/browse/SPL-532
> SPL 532 - A - Inaccessible Scroll Element

- .github/workflows/planner.yml
- app/views/parent-salaries.njk
- test/features/scenarios/adoption/child-live-in-date.spec.js
[SPL-529](https://solirius.atlassian.net/browse/SPL-529)
> SPL-529 - A - Optional Pages

- .github/workflows/planner.yml
- app/assets/javascripts/components/Calendar.vue
- app/assets/javascripts/components/Planner.vue
- app/assets/javascripts/components/ShareLink.vue
- app/assets/sass/application.scss
- app/views/accessibility-statement.njk
- app/views/components/summary-tab-footer.njk
- app/views/parent-salaries.njk
- app/views/planner.njk
**DO NOT MERGE**
https://solirius.atlassian.net/browse/SPL-514
Various fixes on the epic link above
> SPL 514 - WCAG 2.2 improvements

- common/browsered/index.js
https://solirius.atlassian.net/browse/SPL-528
> SPL-528 - A - Page Focus

- package-lock.json
- package.json
See this alert: https://github.com/businessandtrade-partners/spl-planner/security/dependabot/109
> Override elliptic to 6.6.1
